### ISSUE TITLE
git commit log 里面如果有引号，则生成的version info会编译不过

### ISSUE THREAD

**Issue by huahang** [chen3feng/typhoon-blade#127]
extern const char* const kSvnInfo[2] = {"ssh://xxx\n\
    * dev\n\
    commit xxx
    Author: xxx
    Date:   Sat Feb 28 10:45:11 2015 +0800\n\
    \n\
        Merge "xxx"\n\
    "};

**Comment by chen3feng** [comment]
确实是个问题

2015-02-28 15:12 GMT+08:00 huahang <notifications@github.com>:
