### ISSUE TITLE
可以让一个binary使用部分静态库和部分动态库吗？

### ISSUE THREAD

**Issue by acmol** [chen3feng/typhoon-blade#130]
dynamic_link = True会把依赖的所有库设置为动态库，但大部分需求可能是只有部分库需要动态链接。

**Comment by chen3feng** [comment]
prebuilt的库可以是混合模式，源码的因为涉及到符号重复等问题，很难，

2015-03-09 11:47 GMT+08:00 acmol <notifications@github.com>:

**Comment by acmol** [comment]
现在假设我有两个prebuilt库，一个里边是liba.a,一个里边是libb.so，有啥办法用这两个库再加上一个cpp来生成一个binary吗？
cc_binary里加dynamic_link = True会导致找不到liba.so，不加会导致找不到liba.a

**Comment by chen3feng** [comment]
不会，只有一种时就选有的那个

2015-03-24 13:09 GMT+08:00 acmol <notifications@github.com>:

**Comment by cracker-ww** [comment]
@chen3feng 我试验的结果跟acmol一致。你是如何做到main.cc 链接liba.a, 以及libb.so的？ （liba.a与libb.so都是prebuilt ）。多谢。

**Comment by xialeizhou** [comment]
貌似做不到. 痛苦中...

**Comment by chen3feng** [comment]
我这里是好的

2015-07-16 19:15 GMT+08:00 xialeizhou <notifications@github.com>:

**Comment by chen3feng** [comment]
使用的最新版的吗？
