### ISSUE TITLE
在OS X Yosemite Version 10.10.3 下总会弹出要求安装JAVA运行时环境。但是装了也没用。

### ISSUE THREAD

**Issue by acevest** [chen3feng/typhoon-blade#132]
![snip20150512_5](https://cloud.githubusercontent.com/assets/7140471/7583326/e1648016-f8c6-11e4-9695-9010c8900129.png)

**Comment by chen3feng** [comment]
这个，我也不懂，木有mac机。

2015-05-12 16:50 GMT+08:00 acevest <notifications@github.com>:

**Comment by Samurais** [comment]
可以使用 docker来兼容不同环境。https://github.com/Samurais/blade-docker
