### ISSUE TITLE
怎样直接加静态库?

### ISSUE THREAD

**Issue by xialeizhou** [chen3feng/typhoon-blade#133]
静态库: /usr/xxx/libfoo.a
编译: g++ -o bar src/bar.o ../lib/libfoo.a 
?

**Comment by xialeizhou** [comment]
这是个bug吧? 
我手动编译: gcc -L /user/xxx/libfoo.a -lfoo -src/bar.o 
ok.
加在BLADE_ROOT里:
cc_config(
  extra_incs='thirdparty',
  linkflags = ['-L /user/xxx/libfoo.a', '-lfoo']
)
报错无论怎样都提示找不到foo, 是我理解错误?

**Comment by chen3feng** [comment]
-L /user/xxx/

2015-07-09 15:32 GMT+08:00 xialeizhou <notifications@github.com>:

**Comment by xialeizhou** [comment]
多谢, 我试试.

**Comment by Samurais** [comment]
静态库是否可以用
```
prebuilt = True
```,

然后添加
```
lib64_release
```

**Comment by songlong** [comment]
Linking Shared Library build64_debug/src/extractor/libkaka_plugin_extractor.so
/usr/bin/ld: build64_debug/qmodule/libcjson/lib/libcjson.a(libcjson.a-cJSON.o): relocation R_X86_64_32 against `malloc' can not be used when making a shared object; recompile with -fPIC
build64_debug/qmodule/libcjson/lib/libcjson.a: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
scons: *** [build64_debug/src/extractor/libkaka_plugin_extractor.so] Error 1

**Comment by songlong** [comment]
为啥引用第三方库一定要使用-fPIC呢？

**Comment by chen3feng** [comment]
> 为啥引用第三方库一定要使用-fPIC呢？

这个不是blade限制的，是 gnu ld 在 x86_64 下，生成 so 时，要求 .a 里的源文件编译时要带上 -fPIC，否则就会报这个链接错误。加上 -fPIC 重新生成该静态库即可。

**Comment by chen3feng** [comment]
> 静态库是否可以用`prebuilt = True`, 然后添加`lib64_release`文件夹加入libxx.a文件？

是的
