### ISSUE TITLE
Fix building time error for source files with '.S' extension name

### ISSUE THREAD

**Issue by chen3feng** [chen3feng/typhoon-blade#135]
scons use
'gcc --64 xxx.S'
but not
'as -64'
command to assemble '*.S' file.

**Comment by c9n** [comment]
@chen3feng 问个话外题，平时开发都是用 `vim` 么

**Comment by chen3feng** [comment]
是啊
2015年11月3日 16:27，"Lynn" <notifications@github.com>写道：

**Comment by chen3feng** [comment]
开发分支已完成
