### ISSUE TITLE
用blade 生成的的thrift xx.h文件 和 thrift自己生成的不一样

### ISSUE THREAD

**Issue by ppLorins** [chen3feng/typhoon-blade#177]
是关于enum类型的，thrift 定义如下：
![image](https://cloud.githubusercontent.com/assets/5534049/12445028/f9aa7d4a-bf9c-11e5-95ae-a5bdab001454.png)

balde生成的代码：
![image](https://cloud.githubusercontent.com/assets/5534049/12445040/06f643ee-bf9d-11e5-98bd-375bc399499f.png)

thrift 0.9.2生产的代码：
![image](https://cloud.githubusercontent.com/assets/5534049/12445063/33a1cba2-bf9d-11e5-9f08-f44b7753b61f.png)

balde配置的thrift命令路径，和我用的thrift命令路径一样。

用blade生产的那份代码，如果两个enum里面有相同名字的成员，就会报冲突的错误。

这明显是blade问题，怎么解决？

**Comment by ppLorins** [comment]
知道了 , 是blade pure_enum 的配置没有被去掉，改下rules_generator 就好了

**Comment by chen3feng** [comment]
支持可配置如何？

**Comment by chen3feng** [comment]
哪种enum更好？

**Comment by ppLorins** [comment]
支持可配置要修改rules_generator的代码了  没时间看啊。。

**Comment by chen3feng** [comment]
感觉thrift应该支持生成C++的enum class了
