### ISSUE TITLE
BUILD文件如何 根据不同系统，配置不同的deps？

### ISSUE THREAD

**Issue by ppLorins** [chen3feng/typhoon-blade#180]
deps = [               
  .....
    '#pthread',          
    '#xml2',             
    '#ssl',
    '#rt'
  ],

最后的#rt，在mac下实际没有rt库，也不需要。如何让它在mac下忽略这个参数？

**Comment by chen3feng** [comment]
通融方案
import platform

deps = [公共deps...] + enable_if(platform.system()=="Linux", ["#rt"], 其他deps，是可选参数)

enable_if由blade内部预定义，可以直接调用，原型大致如下：
def enable_if(cond, true_part, false_part=[]) return true_part if cond else false_part

**Comment by ppLorins** [comment]
这行应该在哪个脚本里面的哪个逻辑加？    看了一下 没搜到

**Comment by chen3feng** [comment]
deps的值

这行应该在哪个脚本里面的哪个逻辑加？ 看了一下 没搜到

—
Reply to this email directly or view it on GitHub
<https://github.com/chen3feng/typhoon-blade/issues/180#issuecomment-178341111>
.

**Comment by ppLorins** [comment]
没明白，能详细点吗？

**Comment by liuzl** [comment]
BUILD文件的deps值
