### ISSUE TITLE
如何去掉macro redefined  告警？

### ISSUE THREAD

**Issue by ppLorins** [chen3feng/typhoon-blade#184]
blade.conf没搜到相关配置，整个工程目录搜也没搜到。
请教。

**Comment by chen3feng** [comment]
哪个宏啊？
2016年2月17日 10:09 PM，"arthur" <notifications@github.com>写道：

**Comment by ppLorins** [comment]
warning: 'htonll' macro redefined [-Wmacro-redefined]

这个

**Comment by chen3feng** [comment]
blade肯定没有定义这个，检查一下源代码吧，警告信息里也会给出冲突的定义得出处。

2016-02-18 14:41 GMT+08:00 arthur <notifications@github.com>:
