### ISSUE TITLE
how to add -fopenmp when linking?

### ISSUE THREAD

**Issue by lisendong** [chen3feng/typhoon-blade#200]
how to add -fopenmp when linking?

**Comment by lisendong** [comment]
I 've solve the problem:
    cxxflags = ['-std=c++0x' , '-fopenmp', '-fPIC'],
    linkflags = ['-fopenmp'],

**Comment by qqn000** [comment]
linkflags = ['-fopenmp'],   where add it?

**Comment by DoctorQ** [comment]
unrecognized options {'cxxflags': ['-std=c++0x', '-fopenmp', '-fPIC'], 'linkflags': ['-fopenmp']}

**Comment by chen3feng** [comment]
it's global options in cc_config, if you are using it in the target such as cc_binary, member add the 'extra_' prefix
