### ISSUE TITLE
thirdparty编译错误

### ISSUE THREAD

**Issue by icexin** [chen3feng/typhoon-blade#234]
./thirdparty/protobuf-2.4.1/src/google/protobuf/unknown_field_set.h:220:   instantiated from here
./thirdparty/glog-0.3.2/src/glog/logging.h:639: error: comparison between signed and unsigned integer expressions

protobuf中的一个断言触发了符号比较的错误，如何在不修改blade.conf的情况下避免这个问题？
谢谢！

**Comment by WindLeeWT** [comment]
这个错误(警告)产生的原因是gcc的-Wsign-compare，有很多办法可以关闭这个警告选项，可以配置protobuf的cc_library规则: cc_library(name = 'protobuf', srcs = ......, warnings = 'no')，也可以在cc_library或者全局BLADE_ROOT里面单独配置-Wno-sign-compare来关闭这个警告

**Comment by icexin** [comment]
thirdparty下的protobuf已经加了warnings = 'no'，还是会出现这个错误。另外BLADE_ROOT里面怎么配置-Wno-sign-compare？

**Comment by WindLeeWT** [comment]
cc_config(
    warnings = [
        # Add any warning flags you want
        '-Wno-sign-compare',
        ......
    ],

**Comment by chen3feng** [comment]
还有个办法就是修改pb的头文件，加上
#pragma GCC system_header
