### ISSUE TITLE
请教一个问题，需要链接已存在库文件，在BUILD中应该如何配置？

### ISSUE THREAD

**Issue by huangjianxing4hw** [chen3feng/typhoon-blade#252]
请教一个问题，需要链接已存在库文件，应该如何配置，多谢！

deps = [
'../../release/router/ppc/lib/libfeibase.so',
'../../release/router/ppc/lib/libfeivfp.so',
],

这些so已经存在，如：
# ls  ../../release/router/ppc/lib/libfeibase.so

../../release/router/ppc/lib/libfeibase.so

执行blade build 报错：
Blade(error): product/8090/router: Invalid dep in ../../release/router/ppc/lib/libfeibase.so.
Blade(error): product/8090/BUILD: fatal error, exit...

**Comment by Authur** [comment]
cc_library(
  name='feibase',
  prebuilt=True
)

cc_library(
  name='feivfp',
  prebuilt=True
)

cc_library(
  name='xxx',
  deps = [
   ':feibase',
   ':feivfp'
  ]
)

**Comment by supernan** [comment]
请问，编译二进制使用动态时，-L参数在哪里指定呢？

**Comment by supernan** [comment]
请问，编译二进制使用动态库时，-L参数在哪里指定呢？

**Comment by chen3feng** [comment]
extra_linkflags

2017-12-12 19:52 GMT+08:00 supernan <notifications@github.com>:

**Comment by huangjianxing4hw** [comment]
用deps = [
'../../release/router/ppc/lib/libfeibase.so',
'../../release/router/ppc/lib/libfeivfp.so',
],  代替 -L
