### ISSUE TITLE
建议自动引入pb和thrift的路径

### ISSUE THREAD

**Issue by xyz347** [chen3feng/typhoon-blade#270]
cc_targets.py:
    def _export_incs_list(self):
        """_export_incs_list.
        TODO
        """
        deps = self.expanded_deps
        inc_list = []
        for lib in deps:
            # lib is (path, libname) pair.
            if not lib:
                continue

            if not self._dep_is_library(lib):
                continue

            # system lib
            if lib[0] == '#':
                continue

            target = self.target_database[lib]
            if target.type=='thrift_library' or target.type=='proto_library':
                path = os.path.normpath('%s/%s' % (target.build_path, target.path))
                inc_list.append(path)

            for inc in target.data.get('export_incs', []):
                path = os.path.normpath('%s/%s' % (lib[0], inc))
                inc_list.append(path)

        return inc_list

**Comment by WindLeeWT** [comment]
1. 这个和 #include “path/to/foo.pb.h” 的写法有关系，建议的路径是从工作空间的根下写起全路径，这样只需要 dep 该目标即可：

- app/app.cc
```c++
    #include "proto/foo/foo.pb.h"
```

- app/BUILD
```python
        cc_library(
            name = 'app',
            srcs = [...],
            deps = '//proto/foo:foo_proto'
        )
```

- proto/foo/foo.proto
- proto/foo/BUILD
```python
        proto_library(
            name = 'foo',
            srcs = 'foo.proto',
        )
```

2. 仅仅导出 os.path.join(target.build_path, target.path) 也是不够的，比如有的 proto_library 可以这样：
```python
        proto_library(
            name = 'foo',
            srcs = 'path/to/foo.proto',  # srcs 中含有子目录
        )
```
