### ISSUE TITLE
precompiled header support

### ISSUE THREAD

**Issue by xgdgsc** [chen3feng/typhoon-blade#275]
Does this build system support precompiled headers to speed up building?

**Comment by chen3feng** [comment]
No, pch often cause unnecessary header including, (eg, A include file includes all headers).

**Comment by xgdgsc** [comment]
The speed is the point here.

**Comment by chen3feng** [comment]
Yes, but PCH has many problems. such as c/c++ compatibility. if you have any good idea, please no hesitate to let me know.

clang provided a new mechanism, called PTH, to be studied. may be considerable.
http://clang.llvm.org/docs/PTHInternals.html
