### ISSUE TITLE
1.1.1版本无法识别链接符号-fvisibility=hidden

### ISSUE THREAD

**Issue by jfpu** [chen3feng/typhoon-blade#280]
Blade(warning): Auto upgrade failure: /data/home/rtrs//bin/blade: line 78: svn: command not found
Blade(warning): Please svn up /data/bin/typhoon-blade-1.1.1
Blade(warning): You can setenv BLADE_AUTO_UPGRADE=no to disable auto upgrade
Blade: Entering directory `/data/home/rtrs/workspace/ocr_blade'
Blade(warning): /data/home/rtrs/workspace/ocr_blade/BLADE_ROOT: cc_config: unknown config item name: linkflags
Blade(warning): unknown source client type, NOT svn OR git 
Blade(info): loading BUILDs...
**Blade(warning): //idcard/src:idcard.so: unrecognized options {'extra_linkflags': ['-fvisibility=hidden', '-Wl,--exclude-libs,ALL', '-fPIC']}**
Blade(warning): Source file aligner.cpp belongs to both cc_binary face/src:face and cc_binary face/src:face_detect

**Comment by jfpu** [comment]
-fvisibility=hidden 链接SO里隐藏符号功能无法生效

**Comment by WindLeeWT** [comment]
看错误消息是不识别 extra_linkflags，贴 BUILD 文件看看？

**Comment by chen3feng** [comment]
什么类型的目标？可能是不支持extra_linkflags，可以加上。

**Comment by chen3feng** [comment]
猜测是cc_plugin，已经支持
