### ISSUE TITLE
使用blade编译出来的单测运行时报错缺少so

### ISSUE THREAD

**Issue by zhangxiang02** [chen3feng/typhoon-blade#285]
报错信息如下：
xxx_test: error while loading shared libraries: libjvm.so: cannot open shared object file: No such file or directory
使用ldd查看依赖libjvm.so是否可以找到，证明libjvm.so在LD_LIBRARY_PATH中
ldd xxx_test
	linux-vdso.so.1 (0x00007fff08f8d000)
	libjvm.so => /home/rd/zhangxiang/libdfs/xxx/base/libdfs/test_lib/hadoop-client/hadoop/../java6/jre/lib/amd64/server/libjvm.so (0x00007f26e9d17000)
	libz.so.1 => /opt/compiler/gcc-4.8.2/lib/libz.so.1 (0x00007f26e9aff000)
	librt.so.1 => /opt/compiler/gcc-4.8.2/lib/librt.so.1 (0x00007f26e98f7000)
	libpthread.so.0 => /opt/compiler/gcc-4.8.2/lib/libpthread.so.0 (0x00007f26e96d9000)
	libm.so.6 => /opt/compiler/gcc-4.8.2/lib/libm.so.6 (0x00007f26e93d6000)
	libc.so.6 => /opt/compiler/gcc-4.8.2/lib/libc.so.6 (0x00007f26e9029000)
	/opt/compiler/gcc-4.8.2/lib64/ld-linux-x86-64.so.2 (0x00007f26ea922000)
	libdl.so.2 => /opt/compiler/gcc-4.8.2/lib/libdl.so.2 (0x00007f26e8e25000)
我想是blade test运行的方式没有让我新设置LD_LIBRARY_PATH这个变量生效，我要怎么做呢？

**Comment by zhangxiang02** [comment]
直接cd到build64_debug的该单测目录下运行该单测是可以通过的，这个要怎么搞呢？

**Comment by chen3feng** [comment]
没有在外部设置吗？

2017-01-21 16:32 GMT+08:00 Xiang.Zhang <notifications@github.com>:

**Comment by zhangxiang02** [comment]
在外部设置了环境变量好像不管用，有没有其他方式指定

**Comment by zhangxiang02** [comment]
我查看了blade的源码，发现LD_LIBRARY_PATH这个环境变量被覆盖了，我使用的blade版本有点老，跟github的最新版本差距比较大
