### ISSUE TITLE
关于 BLADE_AUTO_UPGRADE， 提个小建议

### ISSUE THREAD

**Issue by gaccob** [chen3feng/typhoon-blade#299]
默认安装之后会提示 warning：

> You can setenv BLADE_AUTO_UPGRADE=no to disable auto upgrade

不太友好，个人建议两种方式：

1. 默认设置为 no，不自动更新，blade 增加内建命令支持手动更新。

2. 修正更新脚本，对 github clone 下来的用户更新 git pull 更妥一点？ 而非 svn up。

> svn_up_info=`svn up --trust-server-cert --non-interactive ${blade_dir} 2>&1`

**Comment by chen3feng** [comment]
是的

**Comment by chen3feng** [comment]
此功能已经移入blade_init，可配置
