### ISSUE TITLE
blade 可以build Go代码吗？

### ISSUE THREAD

**Issue by wangkuiyi** [chen3feng/typhoon-blade#301]

**Comment by WindLeeWT** [comment]
blade 目前是支持 golang 构建的，提供的规则如下：
```python
def go_library(name, srcs, deps=[])

def go_binary(name, srcs, deps=[])

def go_test(name, srcs, deps=[], testdata=[])

# Global configuration in BLADE_ROOT
go_config : {
                'go' : '',  # GO script
                'go_home' : '',  # GOPATH
            },

proto_library_config: {
                'protoc_go_plugin': '',
                # All the generated go source files will be placed
                # into $GOPATH/src/protobuf_go_path
                'protobuf_go_path': '',
            },
```
这些配置和规则都有，但 blade 构建 golang 在实际开发中目前用的还不多，可能存在不完善的地方。我对 golang 构建的理解是：只要遵循 golang 的标准目录布局，使用 go 工具也可以很好的构建代码，而且 go 本身就强调其 build simple & fast compilation `Go provides a model for software construction that makes dependency analysis easy and avoids much of the overhead of C-style include files and libraries.` 

根据我们的一些开发实践，遇到的主要问题就是和 Protobuf 的集成，这需要 [Go support for Protocol Buffers](https://github.com/golang/protobuf) 并且调整 Protobuf 生成代码的目录布局和对 pkg 的处理，我这边有几个例子，没有提交到代码库，需要的话可以在这里的评论和文档里面更新一下
