### ISSUE TITLE
blade

### ISSUE THREAD

**Issue by BillyHu0331** [chen3feng/typhoon-blade#320]
直接在当前目录运行blade build，会报下面这样的错误，
Blade(error): Traceback (most recent call last):
  File "/home/Billy/Desktop/Qmate/Tools/blade/src/blade/blade_main.py", line 373, in main
    exit_code = _main(blade_path)
  File "/home/Billy/Desktop/Qmate/Tools/blade/src/blade/blade_main.py", line 301, in _main
    _check_code_style(opened_files)
  File "/home/Billy/Desktop/Qmate/Tools/blade/src/blade/blade_main.py", line 183, in _check_code_style
    p = subprocess.Popen(('%s %s' % (cpplint, ' '.join(opened_files))), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 7] Argument list too long

要到当前目录的上一层，用blade build dirName 才能编译成功。

**Comment by BillyHu0331** [comment]
哪位大神知道是什么原因导致这样的问题啊？？？

**Comment by WindLeeWT** [comment]
看错误消息是 cpplint 输入的文件太多了，看看当前目录和上一级目录下的 c/c++ 文件列表

**Comment by BillyHu0331** [comment]
![2017-10-23 8 11 10](https://user-images.githubusercontent.com/13376747/31867919-f94261ec-b75c-11e7-8adb-72a317fad3ae.png)
我上一级和当前目录的c/c++文件列表就这些，没有很多吧。 @WindLeeWT

**Comment by WindLeeWT** [comment]
用的是 svn 还是 git？这里是根据 svn/git status 来判断变更或者新增的文件列表，把目前用的 blade 版本发我看看

**Comment by BillyHu0331** [comment]
我这边用的是git， 用的blade版本是最新的

**Comment by WindLeeWT** [comment]
查看一下 .git 目录的位置，是否在 BLADE_ROOT 所在目录下还是某一级子目录，按照一下命令看看输出：
```bash
cd ${directory_where_.git_exist}
git status --porcelain ${subdir}  # subdir is directory from .git parent to Src
```

**Comment by BillyHu0331** [comment]
![2017-10-24 7 59 49](https://user-images.githubusercontent.com/13376747/31918878-7779d49c-b824-11e7-95c4-45b5125d421e.png)

**Comment by WindLeeWT** [comment]
在这个 Qmate 目录下看看这个命令的输出呢：
```bash
git status --porcelain ./
```

**Comment by BillyHu0331** [comment]
![2017-10-24 11 12 15](https://user-images.githubusercontent.com/13376747/31923315-7cf1c7a2-b83f-11e7-8995-e8cd76f75341.png)

这个问题我已经解了，但我还是没找到是哪里出的问题，等我有时间再好好看一下。
还是要谢谢你。非常感谢！ @WindLeeWT
