### ISSUE TITLE
blade编译出来的单测运行时报错缺少so

### ISSUE THREAD

**Issue by BillyHu0331** [chen3feng/typhoon-blade#325]
具体情况是这样的，我用blade编译生成binary时时没有问题的，但是运行binary的时候会报找不到so库的错误，用ldd查看，发现确实找不到对应的so库，手动更改LD_LIBRARY_PATH后，是可以正常运行的，请问我要在编译的时候怎么改BUILD文件，才能更新LD_LIBRARY_PATH，让我的binary可以正常运行？谢谢！
详细截图如下：
![image](https://user-images.githubusercontent.com/13376747/34635101-cdca1cea-f2c5-11e7-9d8c-0b24c0c7f5b7.png)

**Comment by chen3feng** [comment]
是的，本来就需要安装或者配置环境变量等，也可以通过extra_linkflags用rpath连接选项控制，具体搜索rpath和rpath_link

2018-01-06 9:45 GMT+08:00 BillyHu0331 <notifications@github.com>:
