### ISSUE TITLE
请问如何解决thrift 0.8编译出来的C++文件含有gen_cpp路径的问题

### ISSUE THREAD

**Issue by CaesarTang** [chen3feng/typhoon-blade#326]
使用thrift 0.9编译出来的thrift IDL C++文件不含gen_cpp路径；
而0.8版本的编译出来含有gen_cpp路径，请问如果使用blade进行构建，同时使用thrift 0.8版本呢？

**Comment by CaesarTang** [comment]
@guanqun @brianli @huahang @buaaliyi @vonnyfly 各位有看到的帮忙解答一下哈~ 多谢多谢

**Comment by guanqun** [comment]
I haven't used this tool for a long time, please ask the active maintainer for feedback. :)

**Comment by WindLeeWT** [comment]
贴一下输出的 cpp 文件路径看看，建议还是升级 thrift-0.9 吧，如果确实需要保持 0.8 的话可以修改一下代码并替换 blade.zip，[thrift 输出的 cpp 文件路径判断在](https://github.com/chen3feng/typhoon-blade/blob/5a002f995e5ec220098ed61d5c161a0cdeff5d72/src/blade/thrift_helper.py#L87)
```python
def get_generated_cpp_files(self):
        thrift_name = self.src[:-7]
        files = ['%s_constants.cpp' % thrift_name,
                 '%s_constants.h' % thrift_name,
                 '%s_types.cpp' % thrift_name,
                 '%s_types.h' % thrift_name]
        dir = os.path.dirname(thrift_name)  # Modify here for your generated path
        for service in self.services:
            files.append(os.path.join(dir, '%s.cpp' % service))
            files.append(os.path.join(dir, '%s.h' % service))

        return files
```

**Comment by chen3feng** [comment]
bug，升级到thrift新版

2018年1月15日 19:22，"CaesarTang" <notifications@github.com>写道：
