### ISSUE TITLE
.cc文件内全局变量在预编译期未被初始化

### ISSUE THREAD

**Issue by joeylichang** [chen3feng/typhoon-blade#329]
C++11/gcc5.3.1，出现如下问题：A.cc、B.cc，分别初始化了两个 相同类型的对象，且A在程序的调用路径上，B不在。则A中的对象会被调用构造函数，B中的对象不会被调用构造函数。

使用blade编译，且没有添加可疑的编译选项，请问有遇到过吗？

**Comment by joeylichang** [comment]
加上 link_all_symbols 之后，在连接阶段 ，系统调用报未定义错误
rte_eth_pcap.c:(.text+0xd2a): undefined reference to `pcap_open_live'
还需要其他的参数吗？

**Comment by chen3feng** [comment]
那说明还需要链接pcap的库

2018-04-08 10:01 GMT+08:00 joeylichang <notifications@github.com>:

**Comment by joeylichang** [comment]
谢谢 link_all_symbols 正解
