### ISSUE TITLE
undefined reference to `LZ4_compressBound'

### ISSUE THREAD

**Issue by joeylichang** [chen3feng/typhoon-blade#330]
主程序连接阶段，报错
`…………thirdparty/seastar/rpc/lz4_compressor.cc:47: undefined reference to `LZ4_compressBound'`

第三方依赖的源文件lz4_compressor.cc中，#include <lz4.h>，并且/usr/include 包含该文件，thirdparty/seastar 目录下编译没问题。
thirdparty/seastar/rpc/BUILD中添加link_all_symbols=True，之后 主目录连接报错如上。
在主程序BUILD文件中ins中添加 /usr/include ，extra_linkflags中添加'-Wl,--rpath=/usr/bin', 同样报错
请问有什么办法解决吗？

谢谢

**Comment by WindLeeWT** [comment]
这个链接错误是说找不到 lz4 的库，需要参考 https://github.com/lz4/lz4/blob/master/INSTALL 来安装 lz4 的 lib，并检查改 lib 是否存在于 /usr/lib 或者 /usr/local/lib 或者任意指定路径下，非系统路径需要配置 LD_LIBRARY_PATH 等

**Comment by chen3feng** [comment]
看起来是缺少lzma的库，也依法修改即可
