### ISSUE TITLE
gen_rule没有在cc_binary build之前执行

### ISSUE THREAD

**Issue by boswelyu** [chen3feng/typhoon-blade#331]
gen_rule里面配置了一个命令，cc_binary也依赖了这个gen_rule，但是发现gen_rule里面的命令总是在cc_binary中指定的编译命令执行完成之后才被执行。
gen_rule里面的命令的作用是生成一些cpp文件，这些文件也出现在cc_binary中的源文件列表中，我们希望先运行cmd，然后用生成的最新的cpp文件参与cc_binary的编译。

**Comment by chen3feng** [comment]
有没有用到它的outs？

boswelyu <notifications@github.com> 于 2018年4月13日周五 18:57写道：

**Comment by boswelyu** [comment]
补充一点，我感觉有可能是多线程的问题。我并没有仔细看代码，但是从表现上看，好像是同时启动的多个编译线程，并不是每一个都会等依赖的任务完成才继续进行。

**Comment by WindLeeWT** [comment]
由于实现上的限制，blade 并不会自动检查 srcs 中的源文件从而建立起期望的依赖关系，改为如下：
```python
gen_rule(
    name = 'to_lua',
    cmd  = 'Zone/src/tolua.sh',
    outs = [
        'script/l_script_api.cpp',  # generated within build output directory
    ],
)

cc_binary(
    name = 'zone_svr',
    srcs = [
         ......
         'script/l_script_api.cpp',
    ],
    deps = [
        ':to_lua',
    ]
)
```
生成文件在 blade 中是放在 build 目录下，另外由于文件残留的原因，建议改为如上 BUILD 后，清空 build 目录再重新构建一次

**Comment by boswelyu** [comment]
感谢回复。我在cc_binary里面添加了依赖项to_lua，但是表现还是和以前一样的。我又观察了一下，觉得问题应该是这样的：
在构建cc_binary指定的目标的时候，一开始就对cc_binary的srcs指定的源文件执行了生成目标文件的过程，然后（或者同时）去递归地执行deps中的目标的构建过程，然后cc_binary的链接过程会在所有的deps都完成了构建之后才会继续。这在deps中都是生成的库文件的时候是没有问题的。
但是在上面的情况下，blade并不知道cc_binary中srcs中的 l_script_api.cpp文件是to_lua任务生成的，所以就没法保证只有在to_lua都执行完成之后再开始对l_script_api.cpp文件的编译动作。

所以，感觉这种情况下，我们需要把to_lua也弄成一个静态链接库让cc_binary去依赖。

除此之外，请问目前还有什么其他的配置方法能让to_lua命令在cc_binary编译过程开始之前就先执行完吗？

**Comment by WindLeeWT** [comment]
嗯，你说的这个问题我记得之前改了一次，你用的是最新的 develop 分支的代码么？此外，有个办法就是把这个生成的文件独立出来，写成单独的 cc_library：
```python
gen_rule(
    name = 'to_lua',
    cmd  = 'Zone/src/tolua.sh',
    outs = [
        'script/l_script_api.cpp',  # generated within build output directory
    ],
)

cc_library(
    name = 'script_api',
    srcs = 'script/l_script_api.cpp',
    deps = [
        ':to_lua',
    ]
)

cc_binary(
    name = 'zone_svr',
    srcs = [
         ......
         # 'script/l_script_api.cpp',
    ],
    deps = [
        ......
        ':script_api',
    ]
)
```

**Comment by boswelyu** [comment]
"这里我想到一个可能的问题是，你的源代码目录下有 script/l_script_api.cpp 么？有的话应该删除，这个源文件是动态生成的，blade 会自动检查 script/l_script_api.cpp 位于生成目录下还是存在于源代码目录，两个都存在时会产生冲突"

**Comment by WindLeeWT** [comment]
我理解你的问题所在了，这里问题的关键在 tolua.sh，在 tolua.sh 中使用了涉及目标的文件路径，正确的做法应该是使用 gen_rule 支持的 $SRCS 和 $OUTS，这里实际执行时 blade 会自动替换为真实的输入文件（srcs）和输出（outs）路径：
```python
gen_rule(
    name = 'to_lua',
    cmd  = 'Zone/src/tolua.sh $OUTS',   # In tolua.sh, you should use $1 as the final output cpp path instead of a path by hand
    outs = [
        'script/l_script_api.cpp',  # generated within build output directory
                                    # $OUTS will be build64_release/....../script/l_script_api.cpp
    ],
)

cc_library(
    name = 'script_api',
    srcs = 'script/l_script_api.cpp',
    deps = [
        ':to_lua',
    ]
)

cc_binary(
    name = 'zone_svr',
    srcs = [
         ......
         # 'script/l_script_api.cpp',
    ],
    deps = [
        ......
        ':script_api',
    ]
)
```

**Comment by boswelyu** [comment]
非常感谢！问题按照上面的方案解决了。
其实我们的to_lua 中outs有多个文件，使用$OUTS会有多个目标目录，所以我们最终使用了$TARGET，然后把最后出现的文件名移除得到目录名，作为to_lua脚本生成文件的目标目录。
