### ISSUE TITLE
为什么gcc版本大于4.5时需要静态链接libgcc, libstdc++？

### ISSUE THREAD

**Issue by Lunewcome** [chen3feng/typhoon-blade#335]
如题。

**Comment by chen3feng** [comment]
不是gcc版本＞4.5需要静态链接，而是都希望静态链接，因为这样方便部署。4.5以下不静态链接是因为不支持这两个选项（也有办法实现但是没有做）

Lunewcome <notifications@github.com> 于 2018年5月3日周四 10:47写道：
