### ISSUE TITLE
BLADE构建的工程，IDE&VIM 找不到合适的语义补全、语法检查插件

### ISSUE THREAD

**Issue by mickeyandkaka** [chen3feng/typhoon-blade#336]
大多数插件都只支持make类，或者自己填写include信息来描述工程。
然而，当若干大型工程项目全部用BLADE构建的话，几乎所有有用插件基本GG，只能通过比较弱的符号索引暂时替代。

我想了解下腾讯，或者大家是怎么解决这个问题的。毕竟现在不是上古时代了，基于工程，语义的补全&静态动态检查还是非常有必要的，不然只能依赖于程序员人肉了。

如果我错过了什么也欢迎指出帮助更高效的开发。

**Comment by chen3feng** [comment]
" locate project dir by BLADE_ROOT file
functio! FindProjectRootDir()
    let rootfile = findfile("BLADE_ROOT", ".;")
    " in project root dir
    if rootfile == "BLADE_ROOT"
        return ""
    endif
    return substitute(rootfile, "/BLADE_ROOT$", "", "")
endfunction

" set path automatically
function! AutoSetPath()
    let project_root = FindProjectRootDir()
    if project_root != ""
        exec "setlocal path+=" . project_root
    endif
endfunction
autocmd FileType {c,cpp} nested call AutoSetPath()

**Comment by chen3feng** [comment]
参加tools/.vimrc
