### ISSUE TITLE
在3.10.107-1-tlinux2环境下，执行blade build报错，提示没有 -lstdc++

### ISSUE THREAD

**Issue by husonchen** [chen3feng/typhoon-blade#337]
Blade(warning): Auto upgrade failure: /root/bin/blade: line 78: svn: command not found
Blade(warning): Please svn up /data/husonchen/code/blade/typhoon-blade-develop
Blade(warning): You can setenv BLADE_AUTO_UPGRADE=no to disable auto upgrade
Blade(warning): unknown source client type, NOT svn OR git
Blade(info): loading BUILDs...
Blade(info): Use GSL CBLAS.
Blade(info): loading done.
Blade(info): analyzing dependency graph...
Blade(info): analyzing done.
Blade(info): generating build rules...
Blade(info): CPP=cpp
Blade(info): CC=gcc
Blade(info): CXX=g++
Blade(info): LD=g++
Blade(info): generating done.
Blade(info): tunes the parallel jobs number(-j N) to be 8
scons: Reading SConscript files ...
Blade(warning): Failed to get version control info in .
Blade(warning): Failed to get version control info in thirdparty
scons: done reading SConscript files.
scons: Building targets ...
scons: building associated VariantDir targets: build64_release
Linking Program build64_release/common-ut
**/usr/bin/ld: cannot find -lstdc++**
collect2: error: ld returned 1 exit status
src/common/gen-commit-info.sh build64_release/src/common/commit-info.h
scons: *** [build64_release/common-ut] Error 1
scons: building terminated because of errors.
Blade(error): building failure
Blade(info): cost time is 0:00:03s

**Comment by chen3feng** [comment]
没有安装libstdc++的静态库
yum install libstdc++-static

**Comment by daiziyi** [comment]
centos7.3 下安装glibc静态库，解决
`yum install glibc-static`

**Comment by chen3feng** [comment]
已整理到FAQ
