### ISSUE TITLE
protobuf构建后运行时异常

### ISSUE THREAD

**Issue by SummonY** [chen3feng/typhoon-blade#402]
***.proto编译时自动生成pb.h和pb.cc，而非预编译，运行时出现如下异常：

libprotobuf ERROR google/protobuf/descriptor_database.cc:57] File already exists in database: ***.proto

libprotobuf FATAL google/protobuf/descriptor.cc:862] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: generated_database_->Add(encoded_file_descriptor, size):

**Comment by WindLeeWT** [comment]
请给出一个可重现的项目例子，另外 blade 负责按照 BUILD 规则生成目标，具体的运行错误需要看具体的项目和文件组织

**Comment by chen3feng** [comment]
同一个pb.cc进了不同的链接结果，又一起加载，比如主程序和动态链接库，或者2个不同的动态链接库

Summon Yang <notifications@github.com> 于 2018年10月17日周三 21:35写道：

**Comment by denis1008** [comment]
> c进了不同的链接结果，又一起加载，比如主程序和动态

请问如何解决的?
