### ISSUE TITLE
两个json静态库同时链接到bin文件导致连接失败怎么处理？

### ISSUE THREAD

**Issue by hypeaches** [chen3feng/typhoon-blade#403]
我的一个项目，bintest依赖libtestlib、libmyutil和libmypublic；libtestlib依赖libmypublic；libmyutil依赖libmypublic。这是基本的依赖关系。
libtestlib的BUILD文件配置了对json库的依赖'//myproject/liba/third64/json-cpp:json-cpp'，配置了对libjson_libmt.a的依赖，json-cpp目录下包含了libjson-cpp.a、libjson_libmt.a两个文件
libmyutil依赖一个第三方库，该第三方库同样配置了对json的依赖'//myproject/libb/libjsoncpp:jsoncpp'，配置了对libjsoncpp.a的依赖。

编译bintest的时候出现连接错误
Linking Program build64_release/myproject/bintest/bintest
json-cpp/libjson_libmt.a(json_value.o):(.bss+0x0): multiple definition of `Json::Value::null'
libjsoncpp/libjsoncpp.a(json_value.o):tmp/jsoncpp-0.5.0/src/json_value.cpp:55: first defined here
…………
一大堆重复定义错误

第三方库无法修改，我已试过
去除我项目中的json依赖，编译失败
将我项目中的json依赖改为和第三方库相同的json依赖，编译失败

求大神指点一二

**Comment by WindLeeWT** [comment]
库冲突的问题没有好的办法，解决方法就是统一到一个库，尽量调整你的 json 依赖和第三方库的相同吧，如果担心第三库依赖的 jsoncpp 版本比较低，可以尝试升级第三方库并同步升级 jsoncpp
