### ISSUE TITLE
参数配置覆盖问题

### ISSUE THREAD

**Issue by ufosky** [chen3feng/typhoon-blade#414]
参数配置覆盖了整组参数，期望覆盖单个的参数项
我在 `~/.bladerc` 写的配置：
```
cc_config(
  cxxflags=['-std=c++11', '-fpermissive'],
)
```

`BLADE_ROOT` 里的配置是这样：
```
cc_config(
  cxxflags=['-std=c++11'],
)
```

期望的结果参数：
```
-std=c++11 -fpermissive
```

实际结果：
```
-std=c++11
```

**Comment by chen3feng** [comment]
支持追加，参考
https://github.com/chen3feng/typhoon-blade/blob/master/blade.conf
64行
