### ISSUE TITLE
能否导出宏定义

### ISSUE THREAD

**Issue by ufosky** [chen3feng/typhoon-blade#415]
现在可以通过 `export_incs` 向上层传递include path，有没有类似的东西可以传递宏定义什么的，如`export_cppflags`之类的

**Comment by chen3feng** [comment]
为了避免ODR冲突等（带宏和不带的编译结果链接在一起导致的诡异难查的错误），强烈不鼓励在头文件中依赖可变的条件性宏，简易方式
1. blade.conf或者BLADE_ROOT全局配置
2. 直接在库头文件中#define
