### ISSUE TITLE
当dynamic以来是链接的时候代码似乎有问题

### ISSUE THREAD

**Issue by wugh** [chen3feng/typhoon-blade#417]
Hi,
我在看代码的时候发现`cc_targets.py`的`_prebuilt_cc_library`之后，在构建`self._prebuilt_cc_library_scons_rules`之后会去判断我们的`source dynamic so`是否是一个link，如果是一个link那么会用`self._prebuilt_cc_library_dynamic_soname`得到真正的so文件，但是那个`objdump -p `似乎只能支持一次跳转的样子，例如下面的case
```
libtcmalloc.so -> libtcmalloc.so.4
libtcmalloc.so.4 -> libtcmalloc.so.4.1.2
libtcmalloc.so.4.1.2
```
我的prebuild的libtcmalloc.so调用`objdump`之后可以得到`libtcmalloc.so.4 `，但是这个其实还是一个link，感觉这里需要一次循环调用才能找到最后的`so`文件。
不知道我对这块理解是不是有误？

**Comment by WindLeeWT** [comment]
这里不是得到真正的 so，是要得到当前 so 的 [SONAME](https://en.wikipedia.org/wiki/Soname)，以 tcmalloc 为例，虽然实际的文件可能包含多重软连接，但是他们的 SONAME 都是一样的，实际动态链接的程序启动时都会去寻找名字为 SONAME 的 so，还是以这里的 tcmalloc 为例，SONAME 为 libtcmalloc.so.4，而实际的 so 文件是 libtcmalloc.so.4.X.Y

**Comment by wugh** [comment]
好的，谢谢啦！

**Comment by chen3feng** [comment]
是的，应该修一下，谢谢发现
