### ISSUE TITLE
blade build 之前运行一段脚本 支持吗？

### ISSUE THREAD

**Issue by joeylichang** [chen3feng/typhoon-blade#422]
rt，谢谢

**Comment by WindLeeWT** [comment]
什么脚本，可否详细一点举个例子？

**Comment by joeylichang** [comment]
使用 jemalloc源码编译，手动编写blade 总是有问题 ，现在blade build主项目之前 make jemalloc，然后cp在lib64_release下面。
自动生成工具 genlibbuild 会缺省一些编译选项，总是无法正常编译。
或者有办法生成可用的BUILD文件吗 ？

**Comment by WindLeeWT** [comment]
参考 make 的编译命令和选项，按需加到 cc_library 即可，具体来说：

- defs：用于宏定义，比如 `defs = ['-DUSE_CXX11', '-DFOO=BAR']`

- extra_cppflags： 用于额外的编译选项，比如 `extra_cppflags = ['-std=c99']`

- incs：用于额外的头文件路径，从当前目录开始，比如 `incs = ['.', 'include']`
