### ISSUE TITLE
用了下最新的版本，在比较大的项目里使用ninja比scons还慢

### ISSUE THREAD

**Issue by lvlongtao** [chen3feng/typhoon-blade#426]
1.是生成的build.ninja的问题？
2还是说ninja 在parse deps后，并发的时候要依赖中间很多ar产物？

不知道你们使用后的感受是啥。

**Comment by WindLeeWT** [comment]
内部项目中使用 **ninja 1.8.2** 效果提升明显，大概规模是 10w+ 行 build.ninja，c/c++ 编译目标 2w+，链接目标 1w+，还有其他的 protobuf/java/scala/python 构建
依赖关系需要梳理一下，另外也可以通过增加 `-jN` 来提升性能

**Comment by lvlongtao** [comment]
> 内部项目中使用 **ninja 1.8.2** 效果提升明显，大概规模是 10w+ 行 build.ninja，c/c++ 编译目标 2w+，链接目标 1w+，还有其他的 protobuf/java/scala/python 构建
> 依赖关系需要梳理一下，另外也可以通过增加 `-jN` 来提升性能

确实需要梳理依赖关系，多谢。编译飞起来啦
