### ISSUE TITLE
Generate compile_commands.json

### ISSUE THREAD

**Issue by chen3feng** [chen3feng/typhoon-blade#480]
See
https://sarcasm.github.io/notes/dev/compilation-database.html#ninja
https://clang.llvm.org/docs/JSONCompilationDatabase.html
This will improve cooperativeness with other tools, such as editor, ide, build systems, etc.

**Comment by chen3feng** [comment]
Interface design:
```
blade build --generate-compdb
```
write to `blade-bin/compile_commands.json`

Implementation:

`ninja -t compdb <rule names> > blade-bin/compile_commands.json`

The rule names must be provided, see https://github.com/ninja-build/ninja/issues/1024

The rule names can be collected after the rule generation phrase.

**Comment by noahyao1024** [comment]
Hi @chen3feng, is this feature still available?

**Comment by chen3feng** [comment]
Yes, it is.

**Comment by ligen131** [comment]
The command that generates `compile_commands.json` is not the one mentioned above, but rather:
```
blade dump --compdb --tofile=compile_commands.json <YOUR_TARGET_HERE>
```

By the way, if you still can't get clangd or similar tools to properly use the `compile_commands.json` file (such as when the `compile_commands.json` file uses relative paths, or includes some `.o`, `.obj`, `.a` files, etc.), I recommend using the latest version of [Bear](https://github.com/rizsotto/Bear). Just execute:

```
bear -- blade build <YOUR_TARGET_HERE>
```
