### ISSUE TITLE
采用blade编译protobuf出错

### ISSUE THREAD

**Issue by sddi** [chen3feng/typhoon-blade#485]
哈喽，大神，请问下，我git clone protobuf的源码v3.4.0，里面有相关的BUILD文件，但是我采用blade 编译的时候出现如下错误：
~/typhoon-blade/src/blade/load_build_files.py", line 172, in _load_build_file
execfile(build_file, __current_globles, None)
File "thirdparty/protobuf/BUILD", line 3, in 
licenses(["notice"])
NameError: name 'licenses' is not defined

my python version: 2.7.5
protobuf version: 3.4.0

想问下这个有没有碰到，怎么解决的呀。

**Comment by chen3feng** [comment]
哦，这是因为pb高版本支持用bazel编译，bazel的构建脚本也是BUILD文件，需要适当修改，你留个email，我发你一份改好的3.4.1的代码包。

**Comment by sddi** [comment]
@chen3feng  邮箱：sddi1989@126.com
