### ISSUE TITLE
jemalloc用blade 编译问题

### ISSUE THREAD

**Issue by joeylichang** [chen3feng/typhoon-blade#491]
https://github.com/jemalloc/jemalloc/wiki/Use-Case:-Introspection-Via-mallctl*()

cc ex_mallctl.c -o ex_mallctl -I${JEMALLOC_PATH}/include -L${JEMALLOC_PATH}/lib \
-Wl,-rpath,${JEMALLOC_PATH}/lib -ljemalloc

想添加-I${JEMALLOC_PATH}/include -L${JEMALLOC_PATH}/lib \
-Wl,-rpath,${JEMALLOC_PATH}/lib -ljemalloc 这些编译选项在BUILD文件中

如下：
extra_linkflags = [
        '-I=/usr/local/include/jemalloc/',
        '-L=/usr/local/lib/back',
        '-Wl',
        '-rpath=/usr/local/lib/back',
        '-l=jemalloc',
    ],

编译扔失败，报错“error: 'mallctl' was not declared in this scope"

在我的环境上编译环境上编译demo是没有问题的
怀疑是BUILD文件写的那里不对。

**Comment by chen3feng** [comment]
linkflags只作用于编译后的链接阶段。
如果需要用到这么多flags，通常是jemalloc自身的BUILD规则没写好。
