### ISSUE TITLE
pb-3.x 版本编译问题

### ISSUE THREAD

**Issue by sddi** [chen3feng/typhoon-blade#493]
哦，这是因为pb高版本支持用bazel编译，bazel的构建脚本也是BUILD文件，需要适当修改，你留个email，我发你一份改好的3.4.1的代码包。
辛苦发一份到邮箱 sddi1989@126.com  谢谢大神~~~

_Originally posted by @chen3feng in https://github.com/chen3feng/typhoon-blade/issues/485#issuecomment-470134459_

**Comment by chen3feng** [comment]
放这里好了
[pb3.4.1-and-deps.tbz.zip](https://github.com/chen3feng/typhoon-blade/files/2953197/pb3.4.1-and-deps.tbz.zip)
