### ISSUE TITLE
make output dir configurable

### ISSUE THREAD

**Issue by yeshunping** [chen3feng/typhoon-blade#9]
There are four output dirs now, (for different -m -p),
I suggest name output target dirs configurable, and make them subdirs of the same output ROOT dir, such as
BLADE_OUT/32opt
BLADE_OUT/64opt
BLADE_OUT/32dbg
BLADE_OUT/64dbg

we can make BLADE_OUT hidden to avoid dirtying svn

**Comment by chen3feng** [comment]
done
